import { test, expect } from '@playwright/test'

for (const [id, cols, count] of [
	[1, 8, 10],
	[2, 12, 10]
] as const) {
	test(`map ${id}: hydration, movement, cancellation, turns and fresh navigation`, async ({ page }) => {
		const errors: string[] = []
		page.on('pageerror', (error) => errors.push(error.message))
		await page.goto(`/play/${id}/`)
		await expect(page.locator('[data-cell]')).toHaveCount(cols * 8)
		await expect(page.locator('[data-unit]')).toHaveCount(count)
		await page.locator('[data-cell="1"]').click()
		await expect(page.getByRole('button', { name: 'Cancel move', exact: true })).toBeEnabled()
		await page.locator('[data-cell="1"]').press('ArrowDown')
		await expect(page.locator(`[data-cell="${1 + cols}"] [data-unit="1"]`)).toBeVisible()
		await page.getByRole('button', { name: 'Cancel move', exact: true }).click()
		await expect(page.locator('[data-cell="1"] [data-unit="1"]')).toBeVisible()
		await page.getByRole('button', { name: 'End round', exact: true }).click()
		await expect(page.getByText('Round 2', { exact: true })).toBeVisible()
		await page.getByRole('link', { name: '← Pixel’s War' }).click()
		await page.getByRole('link', { name: new RegExp(id === 1 ? 'The Rectangular Map' : 'The Squared Map') }).click()
		await expect(page.getByText('Round 1', { exact: true })).toBeVisible()
		await expect(page.locator('[data-cell]')).toHaveCount(id === 1 ? 96 : 64)
		expect(errors).toEqual([])
		const width = await page.evaluate(() => ({ scroll: document.documentElement.scrollWidth, viewport: innerWidth }))
		expect(width.scroll).toBeLessThanOrEqual(width.viewport)
	})
}

for (const [id, cols, rows] of [
	[3, 10, 10],
	[4, 14, 7],
	[5, 12, 9],
	[6, 9, 11],
	[7, 16, 7],
	[8, 10, 13]
] as const) {
	test(`map ${id}: renders the complete new battlefield without horizontal overflow`, async ({ page }) => {
		await page.goto(`/play/${id}/`)
		await expect(page.locator('[data-cell]')).toHaveCount(cols * rows)
		await expect(page.locator('[data-unit]')).toHaveCount(10)
		await expect(page.getByText('Round 1', { exact: true })).toBeVisible()
		const width = await page.evaluate(() => ({ scroll: document.documentElement.scrollWidth, viewport: innerWidth }))
		expect(width.scroll).toBeLessThanOrEqual(width.viewport)
	})
}

test('selecting a unit does not shift or resize the battlefield', async ({ page }) => {
	await page.setViewportSize({ width: 1200, height: 540 })
	await page.goto('/play/7/')
	const board = page.locator('.board')
	const panel = page.getByRole('complementary', { name: 'Cell statistics' })
	const before = await board.boundingBox()
	const panelBox = await panel.boundingBox()
	await page.locator('[data-cell="1"]').click()
	const after = await board.boundingBox()
	expect(before).not.toBeNull()
	expect(panelBox).not.toBeNull()
	expect(after).not.toBeNull()
	expect(before!.y).toBeCloseTo(panelBox!.y, 1)
	expect(after!.x).toBeCloseTo(before!.x, 1)
	expect(after!.width).toBeCloseTo(before!.width, 1)
})

test('how-to-play dialog replaces the permanent control hint', async ({ page }) => {
	await page.goto('/play/1/')
	await expect(page.getByText('Select a unit, then click adjacent blue cells')).toHaveCount(0)
	await page.getByRole('button', { name: 'How to play', exact: true }).click()
	const dialog = page.getByRole('dialog', { name: 'How to play', exact: true })
	await expect(dialog).toBeVisible()
	await expect(dialog.getByRole('heading', { name: 'Touch and mouse', exact: true })).toBeVisible()
	await expect(dialog.getByRole('heading', { name: 'Keyboard', exact: true })).toBeVisible()
	await expect(dialog.getByText('Arrow keys or ZQSD', { exact: true })).toBeVisible()
	const qwerty = dialog.getByRole('button', { name: 'QWERTY · WASD', exact: true })
	await qwerty.click()
	await expect(qwerty).toHaveAttribute('aria-pressed', 'true')
	await expect(dialog.getByText('Arrow keys or WASD', { exact: true })).toBeVisible()
	await page.keyboard.press('Escape')
	await expect(dialog).toHaveCount(0)
	await page.locator('[data-cell="1"]').click()
	await page.locator('[data-cell="1"]').press('ArrowDown')
	await page.locator('[data-cell="9"]').press('w')
	await expect(page.locator('[data-cell="1"] [data-unit="1"]')).toBeVisible()
	await page.reload()
	await page.getByRole('button', { name: 'How to play', exact: true }).click()
	await expect(page.getByRole('button', { name: 'QWERTY · WASD', exact: true })).toHaveAttribute('aria-pressed', 'true')
})

test('capture city and factory, earn income and purchase through the dialog', async ({ page }) => {
	const errors: string[] = []
	page.on('pageerror', (error) => errors.push(error.message))
	await page.goto('/play/1/')
	const cell = (index: number) => page.locator(`[data-cell="${index}"]`)
	const capture = () => page.getByRole('button', { name: 'Capture', exact: true }).click()
	const end = () => page.getByRole('button', { name: 'End round', exact: true }).click()
	await cell(2).click()
	await cell(10).click()
	await capture()
	await cell(1).click()
	await cell(9).click()
	await cell(8).click()
	await capture()
	await expect(cell(8)).toHaveClass(/-halfcaptured/)
	await end()
	await end()
	await cell(10).click()
	await capture()
	await cell(8).click()
	await capture()
	await expect(cell(8)).toHaveClass(/-capturedby1/)
	await expect(cell(8).getByText('Captured!', { exact: true })).toBeVisible()
	await expect(cell(10).getByText('Captured!', { exact: true })).toBeVisible()
	await expect(cell(10).getByText('+200$', { exact: true })).toHaveCount(0)
	await cell(9).click()
	await page.getByRole('button', { name: 'Confirm move', exact: true }).click()
	await cell(8).click()
	await expect(page.getByRole('dialog', { name: 'Factory' })).toBeVisible()
	await expect(page.getByRole('button', { name: 'Buy Infantry' })).toBeDisabled()
	await expect(page.getByRole('button', { name: 'Buy Anti-air' })).toBeDisabled()
	await expect(page.getByText('Need 200$ more', { exact: true })).toBeVisible()
	await page.getByRole('button', { name: 'Close', exact: true }).click()
	await end()
	await end()
	await cell(8).click()
	await expect(page.getByRole('button', { name: 'Buy Infantry' })).toBeEnabled()
	await page.getByRole('button', { name: 'Buy Infantry' }).click()
	await expect(page.getByRole('dialog')).toHaveCount(0)
	await expect(cell(8).locator('[data-unit]')).toBeVisible()
	await expect(page.locator('[data-unit]')).toHaveCount(11)
	await cell(8).click()
	await cell(8).click()
	await expect(page.getByRole('button', { name: 'Buy Infantry' })).toBeDisabled()
	await expect(page.getByText('Free this factory to build a unit').first()).toBeVisible()
	await page.keyboard.press('Escape')
	await expect(page.getByRole('dialog')).toHaveCount(0)
	expect(errors).toEqual([])
})

test('old board URLs lead to the Svelte game', async ({ page }) => {
	await page.goto('/board-1.html')
	await expect(page).toHaveURL(/\/play\/1\/$/)
	await expect(page.locator('[data-cell]')).toHaveCount(64)
})

test('combat updates rune-driven health, locks controls and clears a dead attacker', async ({ page }) => {
	const errors: string[] = []
	page.on('pageerror', (error) => errors.push(error.message))
	await page.goto('/play/1/')
	const cell = (index: number) => page.locator(`[data-cell="${index}"]`)
	const end = page.getByRole('button', { name: 'End round', exact: true })
	await cell(2).click()
	await cell(10).click()
	await cell(18).click()
	await cell(26).click()
	await end.click()
	await cell(58).click()
	await cell(50).click()
	await cell(42).click()
	await end.click()
	await cell(26).click()
	await cell(34).click()
	await expect(cell(42).getByAltText('Attack target')).toBeVisible()
	await cell(42).click()
	await expect(end).toBeDisabled()
	await expect(cell(42).locator('[data-unit]')).toHaveAttribute('data-health', '164')
	await expect(cell(34).locator('[data-unit]')).toHaveCount(0)
	await expect(end).toBeEnabled()
	await expect(page.getByRole('button', { name: 'Confirm move', exact: true })).toBeDisabled()
	await expect(page.locator('[data-unit]')).toHaveCount(9)
	expect(errors).toEqual([])
})

test('keyboard movement leaves no focused cell after confirming or cancelling', async ({ page }) => {
	await page.goto('/play/1/')
	const origin = page.locator('[data-cell="1"]')
	const destination = page.locator('[data-cell="9"]')
	await origin.click()
	await origin.press('ArrowDown')
	await expect(destination).toBeFocused()
	await destination.press('Enter')
	await expect(page.locator('[data-cell]:focus')).toHaveCount(0)
	await expect(page.locator('[aria-pressed="true"][data-cell]')).toHaveCount(0)
	await destination.click()
	await destination.press('ArrowDown')
	await page.keyboard.press('Escape')
	await expect(page.locator('[data-cell]:focus')).toHaveCount(0)
	await expect(destination.locator('[data-unit]')).toBeVisible()
})

test('captured airport offers aircraft and buys a plane after the tile is freed', async ({ page }) => {
	await page.goto('/play/2/')
	const cell = (i: number) => page.locator('[data-cell="' + i + '"]')
	const end = () => page.getByRole('button', { name: 'End round', exact: true }).click()
	const next = async () => {
		await end()
		await end()
	}
	const capture = () => page.getByRole('button', { name: 'Capture', exact: true }).click()
	await cell(2).click()
	await cell(14).click()
	await capture()
	await next()
	await cell(14).click()
	await capture()
	for (const [i, key] of [
		[26, 'ArrowDown'],
		[27, 'ArrowRight'],
		[28, 'ArrowRight'],
		[29, 'ArrowRight'],
		[30, 'ArrowRight']
	] as const) {
		await cell(i === 26 ? 14 : i - 1).press(key)
		await expect(cell(i).locator('[data-unit]')).toBeVisible()
	}
	await next()
	await cell(30).click()
	await cell(42).click()
	await capture()
	await next()
	await cell(42).click()
	await capture()
	await cell(42).click()
	await expect(page.getByRole('dialog', { name: 'Airport', exact: true })).toBeVisible()
	await expect(page.getByText('Free this airport to build a unit').first()).toBeVisible()
	await page.getByRole('button', { name: 'Close', exact: true }).click()
	await cell(42).click()
	await cell(43).click()
	await page.getByRole('button', { name: 'Confirm move', exact: true }).click()
	await cell(42).click()
	await expect(page.getByRole('dialog', { name: 'Airport', exact: true })).toBeVisible()
	await expect(page.getByRole('button', { name: 'Buy Infantry', exact: true })).toHaveCount(0)
	await expect(page.getByRole('button', { name: 'Buy Helicopter', exact: true })).toBeDisabled()
	await expect(page.getByRole('button', { name: 'Buy Plane', exact: true })).toBeDisabled()
	await page.getByRole('button', { name: 'Close', exact: true }).click()
	for (let i = 0; i < 15; i++) await next()
	await cell(42).click()
	await page.getByRole('button', { name: 'Buy Plane', exact: true }).click()
	await expect(page.getByRole('dialog')).toHaveCount(0)
	await expect(cell(42)).toHaveAttribute('aria-label', /plane/)
})
