import { readMapFixture } from '../map-fixtures'
import { zoomToReadableTiles } from './map-view'
import { test, expect, type Page } from '@playwright/test'
import { turnTransitionDuration } from '../../src/lib/game/timing.ts'

async function endRound(page: Page) {
	await page.getByRole('button', { name: 'End round', exact: true }).click()
	await expect(page.locator('dialog.turn-transition')).toBeVisible()
	await expect(page.locator('dialog.turn-transition')).toHaveCount(0)
}

test('enemy range is inspectable by mouse, touch and keyboard without moving or attacking', async ({ page, isMobile }) => {
	await page.goto('/play/1/')
	const cell = (index: number) => page.locator(`[data-cell="${index}"]`)
	const artillery = cell(63)
	await expect(page.locator('dialog.turn-transition')).toHaveCount(0)
	if (isMobile) await artillery.tap()
	else await artillery.click()
	await expect(artillery).toHaveClass(/inspected/)
	await expect(page.locator('.movement-marker')).toHaveCount(3)
	for (const index of [55, 54, 47]) {
		await expect(cell(index).locator('.movement-marker')).toBeVisible()
		await expect(cell(index)).toHaveAttribute('aria-label', /Reachable by the inspected enemy/)
	}
	await expect(cell(62).locator('.movement-marker')).toHaveCount(0)
	await expect(cell(46).locator('.movement-marker')).toHaveCount(0)
	await expect(page.locator('.attackable')).toHaveCount(16)
	await expect(cell(45)).not.toHaveClass(/attackable/)
	await expect(cell(27)).toHaveClass(/attackable/)
	await expect(cell(54)).not.toHaveClass(/attackable/)
	await expect(cell(26)).not.toHaveClass(/attackable/)
	await expect(artillery.locator('[data-unit]')).toHaveAttribute('data-health', '120')
	await artillery.press('Escape')
	await expect(page.locator('.attackable')).toHaveCount(0)
	await expect(page.locator('.movement-marker')).toHaveCount(0)
	await artillery.press('Enter')
	await expect(artillery).toHaveClass(/inspected/)
	await artillery.click()
	await expect(page.locator('.attackable')).toHaveCount(0)
	await cell(1).click()
	await cell(9).click()
	await artillery.click()
	await expect(cell(9).locator('[data-unit="1"]')).toBeVisible()
	// An enemy mobility dot closes inspection without moving either unit.
	await cell(55).click()
	await expect(cell(9).locator('[data-unit="1"]')).toBeVisible()
	await expect(artillery.locator('[data-unit]')).toHaveCount(1)
	await expect(page.locator('.attackable')).not.toHaveCount(16)
	await artillery.click()
	await artillery.press('Escape')
	await expect(cell(9)).toHaveAttribute('aria-pressed', 'true')
	await page.keyboard.press('Escape')
	await expect(cell(1).locator('[data-unit="1"]')).toBeVisible()
	await expect(page.locator('.attackable')).toHaveCount(0)
})

test('turn transitions block unit selection, production and keyboard input until they finish', async ({ page, isMobile }) => {
	await page.clock.install()
	await page.clock.pauseAt(new Date())
	await page.goto('/play/1/')
	const transition = page.locator('dialog.turn-transition')
	const cell = (index: number) => page.locator(`[data-cell="${index}"]`)
	const tapCell = async (index: number) => {
		const bounds = (await cell(index).boundingBox())!
		const x = bounds.x + bounds.width / 2
		const y = bounds.y + bounds.height / 2
		if (isMobile) await page.touchscreen.tap(x, y)
		else await page.mouse.click(x, y)
	}
	const finishTransition = async () => {
		await expect(transition).toBeVisible()
		await page.clock.runFor(turnTransitionDuration + 100)
		await expect(transition).toHaveCount(0)
	}
	const endTurn = async () => {
		await page.getByRole('button', { name: 'End round', exact: true }).click()
		await finishTransition()
	}
	await expect(transition).toBeVisible()
	await tapCell(1)
	await page.keyboard.press('Tab')
	await page.keyboard.press('Enter')
	await page.keyboard.press('ArrowDown')
	await page.keyboard.press('Escape')
	await expect(cell(1)).toHaveAttribute('aria-pressed', 'false')
	await expect(cell(1).locator('[data-unit="1"]')).toHaveCount(1)
	await finishTransition()
	await cell(1).click()
	await expect(cell(1)).toHaveAttribute('aria-pressed', 'true')
	await cell(9).click()
	await cell(8).click()
	await page.getByRole('button', { name: 'Capture', exact: true }).click()
	await endTurn()
	await endTurn()
	await cell(8).click()
	await page.getByRole('button', { name: 'Capture', exact: true }).click()
	await cell(9).click()
	await page.getByRole('button', { name: 'Confirm move', exact: true }).click()
	await endTurn()
	await page.getByRole('button', { name: 'End round', exact: true }).click()
	await expect(transition).toBeVisible()
	await expect(cell(8)).toHaveClass(/-capturedby1/)
	await tapCell(8)
	await expect(page.getByRole('dialog', { name: 'Army base', exact: true })).toHaveCount(0)
	await finishTransition()
	await cell(8).click()
	await expect(page.getByRole('dialog', { name: 'Army base', exact: true })).toBeVisible()
})

for (const [mapId, columns, rows, name] of [
	[10, 16, 14, 'Watch the Puddles'],
	[11, 18, 14, 'Nice View Up Here'],
	[12, 18, 18, 'The Other Bank']
] as const) {
	test(`${name}: opens from home with reinforced armies and a playable sniper`, async ({ page }, testInfo) => {
		await page.goto('/')
		await page.getByRole('link', { name: new RegExp(name) }).click()
		await page.getByRole('link', { name: 'Play with someone on this device', exact: true }).click()
		await expect(page).toHaveURL(new RegExp(`/play/${mapId}/$`))
		await expect(page.locator('[data-cell]')).toHaveCount(columns * rows)
		await expect(page.locator('[data-unit]')).toHaveCount(mapId === 10 ? 22 : 24)
		await expect(page).toHaveTitle(`Pixel’s War · ${name}`)
		await expect(page.getByRole('group', { name, exact: true })).toBeVisible()
		await expect(page.locator('header h1')).toHaveCount(0)
		for (const type of ['infantry-sniper', 'helicopter', 'anti-air']) await expect(page.locator(`.board .unit-container.-${type}`)).toHaveCount(2)
		const sniperColumn = Math.floor((columns - 11) / 2) + 5
		await page.locator(`[data-cell="${sniperColumn}"]`).click()
		await page.locator(`[data-cell="${columns + sniperColumn}"]`).click()
		if (sniperColumn !== 7) {
			await page.locator(`[data-cell="${columns + 7}"]`).click()
			for (let turn = 0; turn < 2; turn++) await endRound(page)
			await page.locator(`[data-cell="${columns + 7}"]`).click()
		}
		// Watch the Puddles now places this city two rows farther south.
		// Spend one turn crossing the grass before approaching the actual building.
		if (mapId === 10) {
			const stagingCell = page.locator(`[data-cell="${2 * columns + 7}"]`)
			await stagingCell.click()
			await expect(stagingCell.locator('.unit-container.-infantry-sniper')).toBeVisible()
			for (let turn = 0; turn < 2; turn++) await endRound(page)
			await stagingCell.click()
		}
		const captureCell = page.locator(`[data-cell="${(mapId === 10 ? 4 : 2) * columns + 7}"]`)
		await expect(captureCell).toHaveClass(/-building/)
		await captureCell.click()
		await expect(captureCell.locator('.unit-container.-infantry-sniper')).toBeVisible()
		await page.getByRole('button', { name: 'Capture', exact: true }).click()
		await expect(captureCell).toHaveClass(/-halfcaptured/)
		await page.setViewportSize({ width: 360, height: 800 })
		await zoomToReadableTiles(page)
		await expect(page.locator('.minimap').first().locator('[data-minimap-unit]')).toHaveCount(mapId === 10 ? 22 : 24)
		await page
			.locator('.minimap')
			.first()
			.screenshot({ path: testInfo.outputPath(`map-${mapId}.png`) })
		const dimensions = await page.locator('.board-viewport').evaluate((element) => ({ client: element.clientWidth, scroll: element.scrollWidth }))
		expect(dimensions.scroll).toBeGreaterThan(dimensions.client)
	})
}

for (const [id, cols, count] of [
	[1, 8, 10],
	[2, 12, 10]
] as const) {
	test(`map ${id}: hydration, movement, cancellation, turns and fresh navigation`, async ({ page }) => {
		const errors: string[] = []
		page.on('pageerror', (error) => errors.push(error.message))
		await page.goto(`/play/${id}/`)
		await expect(page.locator('[data-cell]')).toHaveCount(cols * 8)
		await expect(page.locator('[data-unit]')).toHaveCount(count)
		await page.locator('[data-cell="1"]').click()
		await expect(page.getByRole('button', { name: 'Cancel move', exact: true })).toBeEnabled()
		await page.locator('[data-cell="1"]').press('ArrowDown')
		await expect(page.locator(`[data-cell="${1 + cols}"] [data-unit="1"]`)).toBeVisible()
		await page.getByRole('button', { name: 'Cancel move', exact: true }).click()
		await expect(page.locator('[data-cell="1"] [data-unit="1"]')).toBeVisible()
		await page.getByRole('button', { name: 'End round', exact: true }).click()
		await expect(page.getByText('Round 2', { exact: true })).toBeVisible()
		await page.getByRole('button', { name: 'Options and help', exact: true }).click()
		await page.getByRole('link', { name: 'Choose another map', exact: true }).click()
		await page.getByRole('link', { name: new RegExp(id === 1 ? 'A Little Stroll' : 'Neighbor Trouble') }).click()
		await page.getByRole('link', { name: 'Play with someone on this device', exact: true }).click()
		await expect(page.getByText('Round 1', { exact: true })).toBeVisible()
		await expect(page.locator('[data-cell]')).toHaveCount(id === 1 ? 96 : 64)
		expect(errors).toEqual([])
		const width = await page.evaluate(() => ({ scroll: document.documentElement.scrollWidth, viewport: innerWidth }))
		expect(width.scroll).toBeLessThanOrEqual(width.viewport)
	})
}

for (const [id, cols, rows] of [
	[3, 11, 11],
	[4, 14, 7],
	[5, 12, 9],
	[6, 9, 11],
	[7, 16, 7],
	[8, 10, 13],
	[9, 12, 10]
] as const) {
	test(`map ${id}: renders the complete new battlefield without horizontal overflow`, async ({ page }) => {
		await page.goto(`/play/${id}/`)
		await expect(page.locator('[data-cell]')).toHaveCount(cols * rows)
		await expect(page.locator('[data-unit]')).toHaveCount(readMapFixture(id).units.length)
		await expect(page.getByText('Round 1', { exact: true })).toBeVisible()
		const width = await page.evaluate(() => ({ scroll: document.documentElement.scrollWidth, viewport: innerWidth }))
		expect(width.scroll).toBeLessThanOrEqual(width.viewport)
	})
}

test('selecting a unit does not shift or resize the battlefield', async ({ page }) => {
	await page.setViewportSize({ width: 1200, height: 540 })
	await page.goto('/play/7/')
	const board = page.locator('.board')
	const panel = page.getByRole('dialog', { name: 'Cell statistics', exact: true })
	const before = await board.boundingBox()
	await expect(panel).toHaveCount(0)
	await page.locator('[data-cell="1"]').click()
	const after = await board.boundingBox()
	expect(before).not.toBeNull()
	await expect(panel).toHaveCount(0)
	await expect(page.getByRole('button', { name: 'Show details', exact: true })).toBeVisible()
	expect(after).not.toBeNull()

	expect(after!.x).toBeCloseTo(before!.x, 1)
	expect(after!.width).toBeCloseTo(before!.width, 1)
})

test('options and help groups settings above synchronized rules without moving the selected unit', async ({ page }) => {
	await page.goto('/play/1/')
	await page.locator('[data-cell="1"]').click()
	await page.getByRole('button', { name: 'Options and help', exact: true }).click()
	const dialog = page.getByRole('dialog', { name: 'Options and help', exact: true })
	await expect(dialog).toBeVisible()
	await expect(dialog.getByRole('heading', { name: 'Options', level: 3, exact: true })).toBeVisible()
	await expect(dialog.getByRole('heading', { name: 'How to play', level: 3, exact: true })).toBeVisible()
	await expect(dialog.locator('details').nth(0)).toHaveJSProperty('open', true)
	await expect(dialog.locator('details').nth(1)).toHaveJSProperty('open', false)
	await dialog.locator('summary').filter({ hasText: 'How to play' }).click()
	await expect(dialog.getByRole('heading', { name: 'Goal', level: 4, exact: true })).toBeVisible()
	await expect(dialog.getByRole('heading', { name: 'Touch and mouse', exact: true })).toBeVisible()
	await expect(dialog.getByText('Arrow keys or ZQSD', { exact: true })).toBeVisible()
	const keyboardLayout = dialog.getByRole('combobox', { name: 'Keyboard movement layout', exact: true })
	await keyboardLayout.selectOption('qwerty')
	await expect(dialog.getByText('Current movement layout: QWERTY · WASD', { exact: true })).toBeVisible()
	await expect(dialog.getByText('Arrow keys or WASD', { exact: true })).toBeVisible()
	await dialog.focus()
	await page.keyboard.press('s')
	await expect(page.locator('[data-cell="1"] [data-unit="1"]')).toHaveCount(1)
	await page.keyboard.press('Escape')
	await expect(dialog).toHaveCount(0)
	await expect(page.locator('[data-cell="1"]')).toHaveAttribute('aria-pressed', 'true')
	await page.locator('[data-cell="1"]').press('ArrowDown')
	await page.locator('[data-cell="9"]').press('w')
	await expect(page.locator('[data-cell="1"] [data-unit="1"]')).toBeVisible()
	await page.reload()
	await page.getByRole('button', { name: 'Options and help', exact: true }).click()
	await expect(keyboardLayout).toHaveValue('qwerty')
})

test('language and audio settings update the UI and persist in session cookies', async ({ page, context }) => {
	await page.goto('/play/1/')
	await page.getByRole('button', { name: 'Options and help', exact: true }).click()
	const sound = page.getByRole('slider', { name: 'Sound', exact: true })
	const music = page.getByRole('button', { name: 'Music off', exact: true })
	await expect(sound).toBeEnabled()
	await expect(music).toBeEnabled()
	await sound.fill('0')
	await expect(sound).toHaveValue('0')
	await expect(music).toBeDisabled()
	await page.getByRole('combobox', { name: 'Language', exact: true }).selectOption('fr')
	await expect(page.getByRole('dialog', { name: 'Options et aide', exact: true })).toBeVisible()
	await page.keyboard.press('Escape')
	await expect(page.getByRole('button', { name: 'Fin du tour', exact: true })).toBeVisible()
	await page.reload()
	await page.getByRole('button', { name: 'Options et aide', exact: true }).click()
	await expect(page.getByRole('slider', { name: 'Son', exact: true })).toHaveValue('0')
	await expect(page.getByRole('button', { name: 'Musique désactivée', exact: true })).toBeDisabled()
	await expect(page.getByRole('combobox', { name: 'Langue', exact: true })).toHaveValue('fr')
	await page.getByRole('slider', { name: 'Son', exact: true }).fill('35')
	await expect(page.getByRole('button', { name: 'Musique désactivée', exact: true })).toBeEnabled()
	await page.reload()
	await page.getByRole('button', { name: 'Options et aide', exact: true }).click()
	await expect(page.getByRole('slider', { name: 'Son', exact: true })).toHaveValue('35')
	const cookie = (await context.cookies()).find(({ name }) => name === 'pixelswars-settings')
	expect(cookie?.expires).toBe(-1)
	expect(decodeURIComponent(cookie?.value ?? '')).toContain('"locale":"fr"')
})

test('the complete home catalog switches between English, German and French', async ({ page }) => {
	await page.goto('/')
	const language = page.getByRole('combobox', { name: 'Language', exact: true })
	await language.selectOption('de')
	await expect(page.getByRole('heading', { name: 'Wähle dein Schlachtfeld', exact: true })).toBeVisible()
	await expect(page.getByRole('heading', { name: 'Raketenwerfer', exact: true })).toBeVisible()
	await expect(page.getByRole('heading', { name: 'Scharfschütze', exact: true })).toBeVisible()
	await expect(page.getByRole('heading', { name: 'Militärbasis', exact: true })).toBeVisible()
	await expect(page.getByText('Bringt jede Runde 200$. Krieg ist teuer.', { exact: true })).toBeVisible()
	await page.getByRole('combobox', { name: 'Sprache', exact: true }).selectOption('fr')
	await expect(page.getByRole('heading', { name: 'Choisissez votre champ de bataille', exact: true })).toBeVisible()
	await expect(page.getByRole('heading', { name: 'Lance-roquettes', exact: true })).toBeVisible()
	await expect(page.getByRole('heading', { name: 'Sniper', exact: true })).toBeVisible()
	await expect(page.getByRole('heading', { name: 'Base armée', exact: true })).toBeVisible()
	const width = await page.evaluate(() => ({ scroll: document.documentElement.scrollWidth, viewport: innerWidth }))
	expect(width.scroll).toBeLessThanOrEqual(width.viewport)
})

test('home offers the complete how-to-play dialog', async ({ page }) => {
	await page.goto('/')
	await page.getByRole('button', { name: 'Learn more', exact: true }).click()
	const dialog = page.getByRole('dialog', { name: 'How to play', exact: true })
	await expect(dialog).toBeVisible()
	await expect(dialog.getByRole('heading', { name: 'Touch and mouse', exact: true })).toBeVisible()
	await expect(dialog.getByRole('heading', { name: 'Keyboard', exact: true })).toBeVisible()
	await expect(dialog.getByText(/Snipers cost/)).toHaveCount(0)
	const scrollArea = dialog.locator('.dialog-content')
	const outerBounds = await dialog.boundingBox()
	const innerBounds = await scrollArea.boundingBox()
	expect(innerBounds!.y - outerBounds!.y).toBeGreaterThanOrEqual(10)
	expect(outerBounds!.y + outerBounds!.height - innerBounds!.y - innerBounds!.height).toBeGreaterThanOrEqual(10)
	await scrollArea.evaluate((element) => element.scrollTo({ top: element.scrollHeight }))
	await expect.poll(() => scrollArea.evaluate((element) => element.scrollHeight - element.scrollTop - element.clientHeight)).toBeLessThanOrEqual(1)
	await page.keyboard.press('Escape')
	await expect(dialog).toHaveCount(0)
})

test('mobile controls keep full-size selects and wide maps use 48px scrollable tiles', async ({ page }) => {
	await page.setViewportSize({ width: 360, height: 800 })
	await page.goto('/play/7/')
	await zoomToReadableTiles(page)
	await expect(page.locator('[data-cell]')).toHaveCount(112)
	await expect(page.getByRole('combobox')).toHaveCount(0)
	await expect(page.locator('.overview').first()).toBeVisible()
	await expect(page.getByRole('button', { name: 'Confirm move', exact: true })).not.toBeVisible()
	const boardBounds = await page.locator('.board-frame').boundingBox()
	const minimapBounds = await page.locator('.overview').first().boundingBox()
	expect(minimapBounds!.y).toBeGreaterThan(boardBounds!.y + boardBounds!.height)
	expect(minimapBounds!.height).toBeLessThanOrEqual(152)
	await page.locator('[data-cell="1"]').click()
	await expect(page.getByRole('button', { name: 'Confirm move', exact: true })).toBeVisible()
	await page.getByRole('button', { name: 'Cancel move', exact: true }).click()
	await expect(page.getByRole('button', { name: 'Confirm move', exact: true })).not.toBeVisible()
	await page.evaluate(() => scrollTo(0, document.documentElement.scrollHeight))
	const barBounds = await page.getByRole('navigation', { name: 'Game controls' }).boundingBox()
	const overviewBounds = (await page.locator('.overview').first().boundingBox())!
	expect(barBounds!.y + barBounds!.height).toBeLessThanOrEqual(overviewBounds.y)
	await expect(page.locator('.tile-preview')).toHaveCount(0)
	await page.getByRole('button', { name: 'Options and help', exact: true }).click()
	const selectHeights = await page.getByRole('combobox').evaluateAll((selects) => selects.map((select) => select.getBoundingClientRect().height))
	expect(selectHeights).toHaveLength(3)
	for (const height of selectHeights) expect(height).toBeGreaterThanOrEqual(44)
	await page.keyboard.press('Escape')
	const dimensions = await page.locator('.board-viewport').evaluate((viewport) => {
		const firstCell = viewport.querySelector<HTMLElement>('[data-cell]')
		return {
			cellWidth: firstCell?.getBoundingClientRect().width ?? 0,
			clientWidth: viewport.clientWidth,
			scrollWidth: viewport.scrollWidth
		}
	})
	expect(dimensions.cellWidth).toBeGreaterThanOrEqual(48)
	expect(dimensions.scrollWidth).toBeGreaterThan(dimensions.clientWidth)
	await expect(page.locator('.board-viewport')).toHaveCSS('scrollbar-width', 'none')
})

test('visual assets preload once and are reused when opening another map', async ({ page }) => {
	let manifestRequests = 0
	page.on('request', (request) => {
		if (new URL(request.url()).pathname.endsWith('/assets/preload-manifest.json')) manifestRequests++
	})
	await page.goto('/play/1/')
	await expect(page.locator('[data-cell]')).toHaveCount(64)
	await page.getByRole('button', { name: 'Options and help', exact: true }).click()
	await page.getByRole('link', { name: 'Choose another map', exact: true }).click()
	await page.getByRole('link', { name: /A Little Stroll/ }).click()
	await page.getByRole('link', { name: 'Play with someone on this device', exact: true }).click()
	await expect(page.locator('[data-cell]')).toHaveCount(96)
	expect(manifestRequests).toBe(1)
})

test('capture city and factory, earn income and purchase through the dialog', async ({ page }) => {
	test.setTimeout(60000)
	const errors: string[] = []
	page.on('pageerror', (error) => errors.push(error.message))
	await page.goto('/play/1/')
	const cell = (index: number) => page.locator(`[data-cell="${index}"]`)
	const capture = () => page.getByRole('button', { name: 'Capture', exact: true }).click()
	const end = () => endRound(page)
	await cell(2).click()
	await cell(10).click()
	await capture()
	await cell(1).click()
	await cell(9).click()
	await cell(8).click()
	await capture()
	await expect(cell(8)).toHaveClass(/-halfcaptured/)
	if (await page.locator('.minimap').count()) await expect(page.locator('.minimap').first().locator('[data-minimap-cell="8"] .terrain-icon')).toHaveCSS('background-image', await cell(8).evaluate((cell) => getComputedStyle(cell).backgroundImage))
	await end()
	await end()
	await cell(10).click()
	await capture()
	await cell(8).click()
	await capture()
	await expect(cell(8)).toHaveClass(/-capturedby1/)
	if (await page.locator('.minimap').count()) await expect(page.locator('.minimap').first().locator('[data-minimap-cell="8"] .terrain-icon')).toHaveCSS('background-image', await cell(8).evaluate((cell) => getComputedStyle(cell).backgroundImage))
	await expect(cell(8).getByText('Captured!', { exact: true })).toBeVisible()
	await expect(cell(10).getByText('Captured!', { exact: true })).toBeVisible()
	await expect(cell(10).getByText('+200$', { exact: true })).toHaveCount(0)
	await cell(9).click()
	await page.getByRole('button', { name: 'Confirm move', exact: true }).click()
	await cell(8).click()
	await expect(page.getByRole('dialog', { name: 'Army base' })).toBeVisible()
	await expect(page.getByRole('button', { name: 'Buy Infantry' })).toBeDisabled()
	await expect(page.getByRole('button', { name: 'Buy Anti-air' })).toBeDisabled()
	await expect(page.getByText('Need 200$ more', { exact: true })).toBeVisible()
	await page.getByRole('button', { name: 'Close', exact: true }).click()
	await end()
	await end()
	await cell(8).click()
	await expect(page.getByRole('button', { name: 'Buy Infantry' })).toBeEnabled()
	await page.getByRole('button', { name: 'Buy Infantry' }).click()
	await expect(page.getByRole('dialog')).toHaveCount(0)
	await expect(cell(8).locator('[data-unit]')).toBeVisible()
	await expect(page.locator('[data-unit]')).toHaveCount(11)
	await cell(8).click()
	await cell(8).click()
	await expect(page.getByRole('button', { name: 'Buy Infantry' })).toBeDisabled()
	await expect(page.getByText('Clear this building to train a unit').first()).toBeVisible()
	await page.keyboard.press('Escape')
	await expect(page.getByRole('dialog')).toHaveCount(0)
	await cell(8).click()
	await cell(16).click()
	await page.getByRole('button', { name: 'Confirm move', exact: true }).click()
	for (let turn = 0; turn < 6; turn++) await end()
	await cell(8).click()
	await expect(page.getByRole('button', { name: 'Buy Sniper', exact: true })).toBeEnabled()
	await page.getByRole('button', { name: 'Buy Sniper', exact: true }).click()
	await expect(cell(8).locator('.unit-sprite')).toHaveCSS('background-image', /infantry-sniper-1\.png/)
	await cell(8).click()
	await expect(page.getByRole('dialog', { name: 'Cell statistics', exact: true })).toHaveCount(0)
	await page.getByRole('button', { name: 'Show details', exact: true }).click()
	await expect(page.getByRole('dialog', { name: 'Cell statistics', exact: true }).getByTestId('preview-range')).toHaveText('2–3')
	expect(errors).toEqual([])
})

test('movement fuel and capture indicators track use, cancellation and turn reset', async ({ page }) => {
	await page.goto('/play/1/')
	const cell = (index: number) => page.locator(`[data-cell="${index}"]`)
	await expect(cell(2).locator('.fuel')).toHaveAttribute('data-level', '4')
	await expect(cell(2).locator('.fuel-fill')).toHaveAttribute('src', /\/icons\/icon-movement\.png$/)
	await expect(cell(2).locator('.fuel-fill')).toHaveCSS('clip-path', 'inset(12% 0px 0px)')
	await expect(cell(2).locator('.capture')).not.toHaveClass(/spent/)
	await expect(cell(0).locator('.capture')).toHaveCount(0)
	await expect(cell(58).locator('.fuel')).toHaveCount(0)
	await cell(2).click()
	await cell(10).click()
	await expect(cell(10).locator('.fuel')).toHaveAttribute('data-level', '3')
	await expect(cell(10)).toHaveAttribute('aria-label', /3\/5 movement points remaining/)
	await cell(18).click()
	await expect(cell(18).locator('.fuel')).toHaveAttribute('data-level', '2')
	await expect(cell(18).locator('.fuel-fill')).toHaveCSS('clip-path', 'inset(50% 0px 0px)')
	await cell(26).click()
	await expect(cell(26).locator('.fuel')).toHaveAttribute('data-level', '0')
	await expect(cell(26).locator('.fuel')).toHaveClass(/spent/)
	await page.getByRole('button', { name: 'Cancel move', exact: true }).click()
	await expect(cell(2).locator('.fuel')).toHaveAttribute('data-level', '4')
	await cell(2).click()
	await cell(10).click()
	await page.getByRole('button', { name: 'Capture', exact: true }).click()
	await expect(cell(10).locator('.capture')).toHaveClass(/spent/)
	await expect(cell(10)).toHaveAttribute('aria-label', /Capture used/)
	await endRound(page)
	await expect(cell(10).locator('.fuel, .capture')).toHaveCount(0)
	await endRound(page)
	await expect(cell(10).locator('.fuel')).toHaveAttribute('data-level', '4')
	await expect(cell(10).locator('.capture')).not.toHaveClass(/spent/)
})

test('spent resources fade in sync across units even when activated at different times', async ({ page }) => {
	await page.goto('/play/1/')
	const bullets = page.locator('.ammo img')
	await expect(bullets.first()).toBeVisible()
	// Isolate animation timing from combat. Activate the spent state on two different units.
	await bullets.first().evaluate((bullet) => bullet.classList.add('spent'))
	await expect.poll(() => bullets.first().evaluate((bullet) => Number(bullet.getAnimations()[0]?.currentTime))).toBeGreaterThan(0)
	await page.waitForTimeout(350)
	await bullets.last().evaluate((bullet) => bullet.classList.add('spent'))
	await page
		.locator('.fuel')
		.first()
		.evaluate((indicator) => indicator.classList.add('spent'))
	await page
		.locator('.capture')
		.first()
		.evaluate((indicator) => indicator.classList.add('spent'))
	const spent = page.locator('.unit-container .spent')
	const assertSynchronized = async () => {
		await expect.poll(() => spent.evaluateAll((bullets) => bullets.map((bullet) => bullet.getAnimations()[0]?.startTime))).toEqual([0, 0, 0, 0])
		const opacity = await spent.evaluateAll((bullets) => bullets.map((bullet) => Number(getComputedStyle(bullet).opacity)))
		for (const value of opacity) expect(value).toBeCloseTo(opacity[0], 4)
	}
	await assertSynchronized()
	await page.emulateMedia({ reducedMotion: 'reduce' })
	await expect(spent.first()).toHaveCSS('animation-name', 'none')
	await page.emulateMedia({ reducedMotion: 'no-preference' })
	await assertSynchronized()
})

test('combat updates rune-driven health, locks controls and clears a dead attacker', async ({ page }) => {
	const errors: string[] = []
	page.on('pageerror', (error) => errors.push(error.message))
	await page.goto('/play/1/')
	const cell = (index: number) => page.locator(`[data-cell="${index}"]`)
	const end = page.getByRole('button', { name: 'End round', exact: true })
	await expect(cell(2).locator('.ammo img')).toHaveCount(2)
	await expect(cell(0).locator('.ammo img')).toHaveCount(1)
	await expect(cell(58).locator('.ammo')).toHaveCount(0)
	await cell(2).click()
	await cell(10).click()
	await cell(18).click()
	await cell(26).click()
	await endRound(page)
	await cell(58).click()
	await cell(50).click()
	await cell(42).click()
	await endRound(page)
	await cell(26).click()
	await cell(34).click()
	await expect(cell(42).getByAltText('Attack target')).toBeVisible()
	const attackerHealth = Number(await cell(34).locator('[data-unit]').getAttribute('data-health'))
	await cell(42).click()
	await expect(cell(34).locator('.ammo')).toHaveAttribute('data-remaining', '1')
	await expect(cell(34).locator('.ammo .spent')).toHaveCount(1)
	await expect(cell(34).locator('.ammo img').first()).toHaveClass(/spent/)
	await expect(cell(34).locator('.ammo img').last()).not.toHaveClass(/spent/)
	await expect(cell(34).locator('.ammo .spent')).toHaveCSS('animation-iteration-count', 'infinite')
	await expect(cell(34).locator('.ammo .spent')).toHaveCSS('animation-timing-function', 'ease-in-out')
	await expect(cell(34).locator('.ammo img:not(.spent)')).toHaveCSS('animation-name', 'none')
	await expect(cell(34)).toHaveAttribute('aria-label', /1\/2 attacks remaining/)
	await expect(cell(42).locator('.damage-indicator')).toHaveText('−16')
	await expect(end).toBeDisabled()
	await expect(end).toHaveText('End round')
	await expect(end).toHaveCSS('opacity', '0.75')
	await expect(end).toHaveCSS('color', 'rgb(17, 26, 20)')
	await expect(cell(42).locator('[data-unit]')).toHaveAttribute('data-health', '164')
	await expect(cell(34).locator('[data-unit]')).toHaveAttribute('data-health', '6')
	await expect(cell(34).locator('.damage-indicator')).toHaveText(`−${attackerHealth - 6}`)
	await expect(end).toBeEnabled()
	await expect(end).toHaveCSS('color', 'rgb(17, 26, 20)')
	await endRound(page)
	await expect(cell(34).locator('.ammo')).toHaveCount(0)
	await expect(cell(42).locator('.ammo img:not(.spent)')).toHaveCount(2)
	await endRound(page)
	await expect(cell(34).locator('.ammo')).toHaveAttribute('data-remaining', '2')
	await expect(cell(34).locator('.ammo .spent')).toHaveCount(0)
	await cell(34).click()
	await cell(42).click()
	await expect(cell(42).locator('[data-unit]')).toHaveAttribute('data-health', '163')
	await expect(cell(34).locator('[data-unit]')).toHaveCount(0)
	await expect(end).toBeEnabled()
	await expect(page.getByRole('button', { name: 'Confirm move', exact: true, includeHidden: true })).toHaveCount(0)
	await expect(page.locator('[data-unit]')).toHaveCount(9)
	await expect(page.locator('.damage-indicator')).toHaveCount(0)
	expect(errors).toEqual([])
})

test('ranged combat keeps its exact target visible through the last shot and retaliation', async ({ page }) => {
	await page.goto('/play/1/')
	const cell = (index: number) => page.locator(`[data-cell="${index}"]`)
	const end = page.getByRole('button', { name: 'End round', exact: true })
	await cell(0).click()
	await cell(8).click()
	await cell(16).click()
	await endRound(page)
	await endRound(page)
	await cell(16).click()
	for (const index of [17, 18, 19, 20]) await cell(index).click()
	await endRound(page)
	await endRound(page)
	await cell(20).click()
	await cell(28).click()
	// Dispatch without Playwright scrolling the target into view for us.
	await page.locator('.board-viewport').evaluate((viewport) => viewport.scrollTo({ left: 0 }))
	await cell(63).evaluate((element) => element.focus({ preventScroll: true }))
	await cell(63).dispatchEvent('click')
	await expect(cell(28).locator('.ammo')).toHaveAttribute('data-remaining', '0')
	await expect(cell(28).locator('.ammo .spent')).toHaveCount(1)
	await page.emulateMedia({ reducedMotion: 'reduce' })
	await expect(cell(28).locator('.ammo .spent')).toHaveCSS('animation-name', 'none')
	await expect(end).toBeDisabled()
	await expect(cell(63)).toHaveClass(/under-fire/)
	await expect(cell(63).getByAltText('Attack target')).toBeVisible()
	await expect(page.getByRole('button', { name: 'Show details', exact: true })).toBeDisabled()
	await expect(page.getByRole('dialog', { name: 'Cell statistics', exact: true })).toHaveCount(0)
	await expect(page.locator('.crosshair')).toHaveCount(1)
	await expect
		.poll(() =>
			cell(63).evaluate((cell) => {
				const target = cell.getBoundingClientRect()
				const viewport = cell.closest('.board-viewport')!.getBoundingClientRect()
				return target.left >= viewport.left - 1 && target.right <= viewport.right + 1
			})
		)
		.toBe(true)
	await expect(cell(28)).toHaveClass(/under-fire/, { timeout: 4000 })
	await expect(cell(28).getByAltText('Attack target')).toBeVisible()
	// The tile thumbnail can update during retaliation, without opening a dialog over combat.
	await cell(9).dispatchEvent('click')
	await expect(page.getByTestId('preview-health')).toHaveCount(0)
	await expect(end).toBeEnabled()
	await expect(page.locator('.under-fire')).toHaveCount(0)
	await expect(page.locator('.crosshair')).toHaveCount(0)
	await page.getByRole('button', { name: 'Show details', exact: true }).click()
	await expect(page.getByRole('dialog', { name: 'Cell statistics', exact: true }).getByRole('heading', { name: 'Hospital', exact: true })).toBeVisible()
	await expect(page.getByTestId('preview-health')).toHaveCount(0)
})

test('movement keys work after closing settings or using zoom without overriding control activation', async ({ page }) => {
	await page.goto('/play/1/')
	const origin = page.locator('[data-cell="1"]')
	const destination = page.locator('[data-cell="9"]')
	const options = page.getByRole('button', { name: 'Options and help', exact: true })
	for (const layout of ['qwerty', 'azerty']) {
		await origin.click()
		await options.click()
		const dialog = page.getByRole('dialog', { name: 'Options and help', exact: true })
		await dialog.getByRole('combobox', { name: 'Keyboard movement layout', exact: true }).selectOption(layout)
		await page.keyboard.press('Escape')
		await expect(dialog).toHaveCount(0)
		// Do not use locator.press(): it would hide the bug by refocusing the board.
		await page.keyboard.press('ArrowDown')
		await expect(destination.locator('[data-unit="1"]')).toBeVisible()
		await expect(destination).toBeFocused()
		await page.keyboard.press(layout === 'qwerty' ? 'W' : 'Z')
		await expect(origin.locator('[data-unit="1"]')).toBeVisible()
		await page.keyboard.press('Escape')
		await origin.click()
		const zoom = page.getByRole('button', { name: 'Zoom in', exact: true }).filter({ visible: true })
		await zoom.click()
		await expect(zoom).toBeFocused()
		await page.keyboard.press('s')
		await expect(destination).toBeFocused()
		await options.focus()
		await page.keyboard.press('Enter')
		await expect(dialog).toBeVisible()
		await expect(destination).toHaveAttribute('aria-pressed', 'true')
		await page.keyboard.press('Escape')
		await page.keyboard.press('Escape')
		await expect(origin.locator('[data-unit="1"]')).toBeVisible()
	}
})

test('keyboard movement leaves no focused cell after confirming or cancelling', async ({ page }) => {
	await page.goto('/play/1/')
	const origin = page.locator('[data-cell="1"]')
	const destination = page.locator('[data-cell="9"]')
	await origin.click()
	await origin.press('ArrowDown')
	await expect(destination).toBeFocused()
	await destination.press('Enter')
	await expect(page.locator('[data-cell]:focus')).toHaveCount(0)
	await expect(page.locator('[aria-pressed="true"][data-cell]')).toHaveCount(0)
	await destination.click()
	await destination.press('ArrowDown')
	await page.keyboard.press('Escape')
	await expect(page.locator('[data-cell]:focus')).toHaveCount(0)
	await expect(destination.locator('[data-unit]')).toBeVisible()
})

test('Escape cancels movement while a non-modal control has focus', async ({ page }) => {
	await page.goto('/play/1/')
	const origin = page.locator('[data-cell="1"]')
	const destination = page.locator('[data-cell="9"]')
	await origin.click()
	await destination.click()
	await expect(destination.locator('[data-unit="1"]')).toBeVisible()
	await page.getByRole('button', { name: 'Options and help', exact: true }).focus()
	await page.keyboard.press('Escape')
	await expect(origin.locator('[data-unit="1"]')).toBeVisible()
	await expect(page.locator('[aria-pressed="true"][data-cell]')).toHaveCount(0)
})

test('captured airport offers aircraft and buys a plane after the tile is freed', async ({ page }) => {
	await page.clock.install()
	await page.goto('/play/2/')
	const cell = (cellIndex: number) => page.locator('[data-cell="' + cellIndex + '"]')
	const end = async () => {
		await page.getByRole('button', { name: 'End round', exact: true }).click()
		await expect(page.locator('dialog.turn-transition')).toBeVisible()
		// Skip the animation while accumulating enough income to buy a plane.
		await page.clock.fastForward(turnTransitionDuration + 100)
		await expect(page.locator('dialog.turn-transition')).toHaveCount(0)
	}
	const next = async () => {
		await end()
		await end()
	}
	const capture = () => page.getByRole('button', { name: 'Capture', exact: true }).click()
	await cell(2).click()
	await cell(14).click()
	await capture()
	await next()
	await cell(14).click()
	await capture()
	for (const [cellIndex, key] of [
		[26, 'ArrowDown'],
		[27, 'ArrowRight'],
		[28, 'ArrowRight'],
		[29, 'ArrowRight'],
		[30, 'ArrowRight']
	] as const) {
		await cell(cellIndex === 26 ? 14 : cellIndex - 1).press(key)
		await expect(cell(cellIndex).locator('[data-unit]')).toBeVisible()
	}
	await next()
	await cell(30).click()
	await cell(42).click()
	await capture()
	await next()
	await cell(42).click()
	await capture()
	await cell(42).click()
	await expect(page.getByRole('dialog', { name: 'Airport', exact: true })).toBeVisible()
	await expect(page.getByText('Clear this building to train a unit').first()).toBeVisible()
	await page.getByRole('button', { name: 'Close', exact: true }).click()
	await cell(42).click()
	await cell(43).click()
	await page.getByRole('button', { name: 'Confirm move', exact: true }).click()
	await cell(42).click()
	await expect(page.getByRole('dialog', { name: 'Airport', exact: true })).toBeVisible()
	await expect(page.getByRole('button', { name: 'Buy Infantry', exact: true })).toHaveCount(0)
	await expect(page.getByRole('button', { name: 'Buy Helicopter', exact: true })).toBeDisabled()
	await expect(page.getByRole('button', { name: 'Buy Plane', exact: true })).toBeDisabled()
	await page.getByRole('button', { name: 'Close', exact: true }).click()
	for (let roundIndex = 0; roundIndex < 15; roundIndex++) await next()
	await cell(42).click()
	await page.getByRole('button', { name: 'Buy Plane', exact: true }).click()
	await expect(page.getByRole('dialog')).toHaveCount(0)
	await expect(cell(42)).toHaveAttribute('aria-label', /plane/i)
	await expect(cell(42).locator('.unit-sprite')).toHaveClass(/airborne/)
	await expect(cell(42).locator('.unit-sprite')).toHaveCSS('animation-name', /idle-hover/)
})

test('scroll arrows navigate a bounded map viewport', async ({ page }) => {
	await page.setViewportSize({ width: 360, height: 600 })
	await page.goto('/play/8/')
	await zoomToReadableTiles(page)
	await expect(page.locator('[data-cell]')).toHaveCount(130)
	const viewport = page.locator('.board-viewport')
	const edge = (direction: string) => page.locator('.scroll-edge.' + direction)
	await expect(edge('left')).toHaveCSS('opacity', '0')
	await expect(page.getByRole('button', { name: 'Scroll left', exact: true })).toBeDisabled()
	await page.getByRole('button', { name: 'Scroll right', exact: true }).click()
	await expect.poll(() => viewport.evaluate((element) => element.scrollLeft)).toBeGreaterThan(0)
	await expect(edge('left')).toHaveCSS('opacity', '1')
	await page.getByRole('button', { name: 'Scroll left', exact: true }).click()
	await expect(edge('left')).toHaveCSS('opacity', '0')
	await viewport.evaluate((viewport) => viewport.scrollTo({ left: 24 }))
	await expect(edge('left')).toHaveCSS('opacity', '0.5')
	const height = await viewport.evaluate((viewport) => ({ visible: viewport.clientHeight, total: viewport.scrollHeight }))
	expect(height.visible).toBeLessThan(height.total)
	await page.setViewportSize({ width: 1400, height: 1200 })
	await page.getByRole('button', { name: 'Show the whole map', exact: true }).click()
	for (const direction of ['left', 'right']) await expect(edge(direction)).toHaveCSS('opacity', '0')
})

test('mobile minimap shows the complete battlefield and repositions without moving units', async ({ page }) => {
	await page.setViewportSize({ width: 360, height: 700 })
	await page.goto('/play/7/')
	await zoomToReadableTiles(page)
	const overview = page.getByRole('button', { name: 'Move the battlefield view', exact: true }).first()

	await expect(page.locator('.minimap')).toHaveCount(1)
	await expect(overview).toBeVisible()
	const boardBounds = await page.locator('.board-frame').boundingBox()
	const minimapBounds = await overview.boundingBox()
	expect(minimapBounds!.y).toBeGreaterThanOrEqual(boardBounds!.y + boardBounds!.height)
	await expect(overview.locator('[data-minimap-unit]')).toHaveCount(10)
	await expect(overview.locator('[data-minimap-cell]')).toHaveCount(112)
	await expect(overview.locator('svg')).toHaveAttribute('viewBox', '0 0 160 70')
	await page.locator('[data-cell="1"]').click()
	await page.locator('[data-cell="17"]').click()
	await expect(overview.locator('[data-minimap-cell="17"] [data-minimap-unit="1"]')).toHaveCount(1)
	await expect(overview.locator('[data-minimap-cell="17"]')).toHaveClass(/selected/)
	await page.getByRole('button', { name: 'Cancel move', exact: true }).click()
	await expect(overview.locator('[data-minimap-cell="1"] [data-minimap-unit="1"]')).toHaveCount(1)
	const initialUnits = await page.locator('[data-unit]').evaluateAll((units) => units.map((unit) => unit.parentElement?.dataset.cell))
	const box = await overview.boundingBox()
	await overview.click({ position: { x: box!.width - 5, y: box!.height / 2 } })
	await expect.poll(() => page.locator('.board-viewport').evaluate((viewport) => viewport.scrollLeft)).toBeGreaterThan(300)
	await expect.poll(() => overview.locator('.visible-area').getAttribute('x')).not.toBe('0.75')
	await overview.press('Home')
	await expect.poll(() => page.locator('.board-viewport').evaluate((viewport) => viewport.scrollLeft)).toBe(0)
	await overview.press('End')
	await expect.poll(() => page.locator('.board-viewport').evaluate((viewport) => viewport.scrollLeft)).toBeGreaterThan(300)
	await overview.press('Home')
	await expect.poll(() => overview.locator('.visible-area').getAttribute('x')).toBe('0.75')
	const dragBounds = await overview.boundingBox()
	await page.mouse.move(dragBounds!.x + 5, dragBounds!.y + dragBounds!.height / 2)
	await page.mouse.down()
	await page.mouse.move(dragBounds!.x + dragBounds!.width - 5, dragBounds!.y + dragBounds!.height / 2, { steps: 5 })
	await page.mouse.up()
	await expect.poll(() => page.locator('.board-viewport').evaluate((viewport) => viewport.scrollLeft)).toBeGreaterThan(300)
	expect(await page.locator('[data-unit]').evaluateAll((units) => units.map((unit) => unit.parentElement?.dataset.cell))).toEqual(initialUnits)
	await page.setViewportSize({ width: 850, height: 900 })
	await page.getByRole('button', { name: 'Show the whole map', exact: true }).click()
	await expect(overview).toBeVisible()
	const fitted = await page.locator('.board-viewport').evaluate((viewport) => ({ width: viewport.clientWidth, height: viewport.clientHeight, totalWidth: viewport.scrollWidth, totalHeight: viewport.scrollHeight }))
	expect(fitted.totalWidth).toBeLessThanOrEqual(fitted.width + 1)
	expect(fitted.totalHeight).toBeLessThanOrEqual(fitted.height + 1)
	await page.setViewportSize({ width: 360, height: 700 })
	await page.getByRole('button', { name: 'Zoom in', exact: true }).click()
	await expect(overview).toBeVisible()
})

test('minimap uses the board terrain variants and each team’s actual unit sprites', async ({ page }, testInfo) => {
	await page.setViewportSize({ width: 360, height: 800 })
	await page.goto('/play/9/')
	await zoomToReadableTiles(page)
	await expect(page.locator('[data-cell]')).toHaveCount(120)
	const terrainSprites = await page.locator('[data-cell]').evaluateAll((cells) => cells.map((cell) => getComputedStyle(cell).backgroundImage))
	const minimapTerrain = await page
		.locator('.minimap')
		.first()
		.locator('[data-minimap-cell] .terrain-icon')
		.evaluateAll((cells) => cells.map((cell) => getComputedStyle(cell).backgroundImage))
	expect(minimapTerrain).toEqual(terrainSprites)
	expect(minimapTerrain.every((sprite) => sprite !== 'none')).toBe(true)
	const boardUnits = await page.locator('[data-unit]').evaluateAll((units) => units.map((unit) => ({ cell: unit.parentElement?.dataset.cell, sprite: getComputedStyle(unit.querySelector('.unit-sprite')!).backgroundImage })))
	const minimapUnits = await page
		.locator('.minimap')
		.first()
		.locator('[data-minimap-unit]')
		.evaluateAll((units) => units.map((unit) => ({ cell: unit.parentElement?.dataset.minimapCell, sprite: `url("${(unit as HTMLImageElement).src}")` })))
	expect(minimapUnits).toEqual(boardUnits)
	for (const sprite of await page
		.locator('.minimap')
		.first()
		.locator('[data-minimap-unit]')
		.evaluateAll((images) => images.map((image) => ({ complete: (image as HTMLImageElement).complete, width: (image as HTMLImageElement).naturalWidth })))) {
		expect(sprite.complete).toBe(true)
		expect(sprite.width).toBeGreaterThan(0)
	}
	await page
		.locator('.minimap')
		.first()
		.screenshot({ path: testInfo.outputPath('minimap.png') })
})

test('home map cards share the tallest height across rows in every language', async ({ page }) => {
	await page.setViewportSize({ width: 1100, height: 900 })
	await page.goto('/')
	for (const locale of ['en', 'fr', 'de']) {
		await page.getByRole('combobox').selectOption(locale)
		const heights = await page.locator('.maps .map').evaluateAll((cards) => cards.map((card) => card.getBoundingClientRect().height))
		expect(Math.max(...heights) - Math.min(...heights)).toBeLessThan(1)
	}
	await page.setViewportSize({ width: 360, height: 800 })
	await expect(page.locator('.maps')).toHaveCSS('grid-auto-rows', 'auto')
})

test('catalog cards share a desktop grid and mountain lists its ranged ground bonus', async ({ page }) => {
	await page.setViewportSize({ width: 1200, height: 900 })
	await page.goto('/')
	const mountain = page.locator('article').filter({ has: page.getByRole('heading', { name: 'Mountain', exact: true }) })
	await expect(mountain.getByText('Range bonus for ranged ground units', { exact: true })).toBeVisible()
	await expect(mountain.getByText('+1', { exact: true })).toBeVisible()
	const cards = await page
		.locator('.catalog')
		.first()
		.locator('article')
		.evaluateAll((cards) =>
			cards.map((card) => {
				const rectangle = card.getBoundingClientRect()
				return { top: rectangle.top, height: rectangle.height, width: rectangle.width }
			})
		)
	for (let index = 1; index < cards.length; index++) {
		expect(cards[index].top).toBe(cards[0].top)
		expect(cards[index].height).toBe(cards[0].height)
		expect(cards[index].width).toBe(cards[0].width)
	}
	const select = page.getByRole('combobox')
	await select.focus()
	await expect(select).toHaveCSS('outline-style', 'solid')
	await expect(select.locator('..')).toHaveCSS('outline-style', 'none')
})
