import { test, expect } from '@playwright/test'

for (const [id, cols, count] of [
	[1, 8, 10],
	[2, 12, 8]
]) {
	test(`map ${id}: hydration, movement, cancellation, turns and fresh navigation`, async ({ page }) => {
		const errors = []
		page.on('pageerror', (error) => errors.push(error.message))
		await page.goto(`/play/${id}/`)
		await expect(page.locator('[data-cell]')).toHaveCount(cols * 8)
		await expect(page.locator('[data-unit]')).toHaveCount(count)
		await page.locator('[data-cell="1"]').click()
		await expect(page.getByRole('button', { name: 'Cancel move', exact: true })).toBeEnabled()
		await page.locator('[data-cell="1"]').press('ArrowDown')
		await expect(page.locator(`[data-cell="${1 + cols}"] [data-unit="1"]`)).toBeVisible()
		await page.getByRole('button', { name: 'Cancel move', exact: true }).click()
		await expect(page.locator('[data-cell="1"] [data-unit="1"]')).toBeVisible()
		await page.getByRole('button', { name: 'End round', exact: true }).click()
		await expect(page.getByText('Round 2', { exact: true })).toBeVisible()
		await page.getByRole('link', { name: '← Pixel’s War' }).click()
		await page.getByRole('link', { name: new RegExp(id === 1 ? 'The Rectangular Map' : 'The Squared Map') }).click()
		await expect(page.getByText('Round 1', { exact: true })).toBeVisible()
		await expect(page.locator('[data-cell]')).toHaveCount(id === 1 ? 96 : 64)
		expect(errors).toEqual([])
		const width = await page.evaluate(() => ({ scroll: document.documentElement.scrollWidth, viewport: innerWidth }))
		expect(width.scroll).toBeLessThanOrEqual(width.viewport)
	})
}

test('capture city and factory, earn income and purchase through the dialog', async ({ page }) => {
	const errors = []
	page.on('pageerror', (error) => errors.push(error.message))
	await page.goto('/play/1/')
	const cell = (index) => page.locator(`[data-cell="${index}"]`)
	const capture = () => page.getByRole('button', { name: 'Capture', exact: true }).click()
	const end = () => page.getByRole('button', { name: 'End round', exact: true }).click()
	await cell(2).click()
	await cell(10).click()
	await capture()
	await cell(1).click()
	await cell(9).click()
	await cell(8).click()
	await capture()
	await expect(cell(8)).toHaveClass(/-halfcaptured/)
	await end()
	await end()
	await cell(10).click()
	await capture()
	await cell(8).click()
	await capture()
	await expect(cell(8)).toHaveClass(/-capturedby1/)
	await cell(9).click()
	await page.getByRole('button', { name: 'Confirm move', exact: true }).click()
	await cell(8).click()
	await expect(page.getByRole('dialog', { name: 'Factory' })).toBeVisible()
	await expect(page.getByRole('button', { name: 'Buy Infantry' })).toBeDisabled()
	await expect(page.getByText('Need 200$ more', { exact: true })).toBeVisible()
	await page.getByRole('button', { name: 'Close', exact: true }).click()
	await end()
	await end()
	await cell(8).click()
	await expect(page.getByRole('button', { name: 'Buy Infantry' })).toBeEnabled()
	await page.getByRole('button', { name: 'Buy Infantry' }).click()
	await expect(page.getByRole('dialog')).toHaveCount(0)
	await expect(cell(8).locator('[data-unit]')).toBeVisible()
	await expect(page.locator('[data-unit]')).toHaveCount(11)
	await cell(8).click()
	await cell(8).click()
	await expect(page.getByRole('button', { name: 'Buy Infantry' })).toBeDisabled()
	await expect(page.getByText('Free this factory to build a unit').first()).toBeVisible()
	await page.keyboard.press('Escape')
	await expect(page.getByRole('dialog')).toHaveCount(0)
	expect(errors).toEqual([])
})

test('old board URLs lead to the Svelte game', async ({ page }) => {
	await page.goto('/board-1.html')
	await expect(page).toHaveURL(/\/play\/1\/$/)
	await expect(page.locator('[data-cell]')).toHaveCount(64)
})

test('combat updates rune-driven health, locks controls and clears a dead attacker', async ({ page }) => {
	const errors = []
	page.on('pageerror', (error) => errors.push(error.message))
	await page.goto('/play/1/')
	const cell = (index) => page.locator(`[data-cell="${index}"]`)
	const end = page.getByRole('button', { name: 'End round', exact: true })
	await cell(2).click()
	await cell(10).click()
	await cell(18).click()
	await cell(26).click()
	await end.click()
	await cell(58).click()
	await cell(50).click()
	await cell(42).click()
	await end.click()
	await cell(26).click()
	await cell(34).click()
	await expect(cell(42).getByAltText('Attack target')).toBeVisible()
	await cell(42).click()
	await expect(end).toBeDisabled()
	await expect(cell(42).locator('[data-unit]')).toHaveAttribute('data-health', '164')
	await expect(cell(34).locator('[data-unit]')).toHaveCount(0)
	await expect(end).toBeEnabled()
	await expect(page.getByRole('button', { name: 'Confirm move', exact: true })).toBeDisabled()
	await expect(page.locator('[data-unit]')).toHaveCount(9)
	expect(errors).toEqual([])
})
