import { test, expect } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { readMap } from '../../src/lib/map-editor/model.ts'

test('owner and team selections stay visible and apply when painting', async ({ page }) => {
	await page.goto('/map-editor/')
	const owner = page.locator('#owner')
	const team = page.locator('#team')
	await expect(owner).toHaveValue('0')
	await expect(team).toHaveValue('1')
	await page.locator('[data-brush="building_city"]').click()
	await owner.selectOption('2')
	await page.locator('[data-cell="0"]').click()
	await expect(owner).toHaveValue('2')
	await expect(page.locator('[data-cell="0"]')).toHaveClass(/-capturedby2/)
	await page.locator('[data-brush="infantry"]').click()
	await team.selectOption('2')
	await page.locator('[data-cell="1"]').click()
	await expect(team).toHaveValue('2')
	await expect(page.locator('[data-cell="1"] img')).toHaveAttribute('src', /infantry-2\.png/)
	await page.locator('#language').selectOption('fr')
	await expect(owner).toHaveValue('2')
	await expect(team).toHaveValue('2')
	await team.selectOption('1')
	await page.locator('[data-cell="2"]').click()
	await expect(team).toHaveValue('1')
	await expect(page.locator('[data-cell="2"] img')).toHaveAttribute('src', /infantry-1\.png/)
	await owner.selectOption('0')
	await page.locator('[data-brush="building_city"]').click()
	await page.locator('[data-cell="3"]').click()
	await expect(owner).toHaveValue('0')
	await expect(page.locator('[data-cell="3"]')).not.toHaveClass(/-capturedby/)
})

test('draw, undo, restore, export and reimport a playable map', async ({ page }, testInfo) => {
	const errors: string[] = []
	page.on('pageerror', (error) => errors.push(error.message))
	await page.goto('/map-editor/')
	await page.locator('#language').selectOption('fr')
	await page.getByLabel('Colonnes', { exact: true }).fill('6')
	await page.getByLabel('Lignes', { exact: true }).fill('6')
	await page.getByRole('button', { name: 'Nouvelle grille', exact: true }).click()
	await page.getByLabel('Nom', { exact: true }).fill('Test map')
	await page.getByLabel('ID', { exact: true }).fill('15')
	await page.getByRole('button', { name: 'Route', exact: true }).click()
	const cell = (index: number) => page.locator(`[data-cell="${index}"]`)
	await cell(12).scrollIntoViewIfNeeded()
	const firstRoad = await cell(12).boundingBox()
	const lastRoad = await cell(17).boundingBox()
	await page.mouse.move(firstRoad!.x + 20, firstRoad!.y + 20)
	await page.mouse.down()
	await page.mouse.move(lastRoad!.x + 20, lastRoad!.y + 20, { steps: 10 })
	await page.mouse.up()
	await expect(page.locator('#board .-road')).toHaveCount(6)
	await page.getByRole('button', { name: 'Annuler', exact: true }).click()
	await expect(page.locator('#board .-road')).toHaveCount(0)
	await cell(12).click()
	await cell(13).click()
	await page.getByLabel('Propriétaire du bâtiment').selectOption('1')
	await page.getByRole('button', { name: 'Champ pétrolier', exact: true }).click()
	await cell(19).click()
	await expect(cell(19)).toHaveClass(/-capturedby1/)
	await page.getByRole('button', { name: 'Infanterie', exact: true }).click()
	await cell(0).click()
	await page.getByRole('combobox', { name: 'Équipe', exact: true }).selectOption('2')
	await cell(35).click()
	await page.reload()
	await expect(page.getByLabel('Nom', { exact: true })).toHaveValue('Test map')
	await expect(page.locator('#board img')).toHaveCount(2)
	const downloadReady = page.waitForEvent('download')
	await page.getByRole('button', { name: '↓ Exporter le JSON', exact: true }).click()
	const download = await downloadReady
	expect(download.suggestedFilename()).toBe('board-15.json')
	const exportPath = testInfo.outputPath('board-15.json')
	await download.saveAs(exportPath)
	const map = readMap(await readFile(exportPath, 'utf8'))
	expect(map.units).toEqual([
		{ type: 'infantry', player: 1, cell: 0 },
		{ type: 'infantry', player: 2, cell: 35 }
	])
	expect(map.cells[19]).toEqual({ classes: ['-building', '-oil-field', '-ongrass'], owner: 1, capturePoints: 20 })
	await page.getByRole('button', { name: 'Nouvelle grille', exact: true }).click()
	await page.getByText('Partir d’une carte', { exact: true }).click()
	await page.locator('#import').setInputFiles(exportPath)
	await expect(page.getByLabel('Nom', { exact: true })).toHaveValue('Test map')
	await expect(page.locator('#board img')).toHaveCount(2)
	await page.locator('#import').setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{"cells": []}') })
	await expect(page.locator('#status')).toHaveClass(/error/)
	await expect(page.locator('#board img')).toHaveCount(2)
	await page.getByRole('combobox', { name: 'Carte du jeu', exact: true }).selectOption('8')
	await page.getByRole('button', { name: 'Charger cette carte', exact: true }).click()
	await expect(page.locator('#board [data-cell]')).toHaveCount(130)
	await page.getByText('JSON à copier', { exact: true }).click()
	await expect(page.getByLabel('JSON de la carte')).toHaveValue(/"id": "8"/)
	expect(readMap(await page.getByLabel('JSON de la carte').inputValue()).id).toBe('8')
	await page.getByText('JSON à copier', { exact: true }).click()
	await page.getByText('Partir d’une carte', { exact: true }).click()
	expect(errors).toEqual([])
	await page.setViewportSize({ width: 1440, height: 1000 })
	await page.getByRole('heading', { level: 1 }).scrollIntoViewIfNeeded()
	await page.screenshot({ path: testInfo.outputPath('map-editor.png') })
})
