import { test, expect } from '@playwright/test'

test('I opens the inspected tile statistics without changing the selection or overlapping options', async ({ page }) => {
	await page.goto('/play/1/')
	const stats = page.getByRole('dialog', { name: 'Cell statistics', exact: true })
	await expect(page.locator('.board')).toBeVisible()
	await page.keyboard.press('i')
	await expect(stats).toHaveCount(0)
	const origin = page.locator('[data-cell="1"]')
	await origin.click()
	const inspect = page.getByRole('button', { name: 'Show details', exact: true })
	await expect(inspect).toHaveAttribute('aria-keyshortcuts', 'I')
	await origin.dispatchEvent('keydown', { key: 'i', ctrlKey: true, bubbles: true })
	await expect(stats).toHaveCount(0)
	await origin.dispatchEvent('keydown', { key: 'i', repeat: true, bubbles: true })
	await expect(stats).toHaveCount(0)
	await page.keyboard.press('i')
	await expect(stats).toBeVisible()
	await expect(stats.getByTestId('preview-health')).toHaveText('100/100')
	await page.keyboard.press('Escape')
	await expect(origin).toHaveAttribute('aria-pressed', 'true')
	await page.keyboard.press('ArrowDown')
	await page.keyboard.press('I')
	await expect(stats).toBeVisible()
	await expect(stats.getByText('3/5', { exact: true })).toBeVisible()
	await page.keyboard.press('Escape')
	await page.keyboard.press('Escape')
	await page.locator('[data-cell="61"]').click()
	await page.keyboard.press('i')
	await expect(stats).toBeVisible()
	await expect(stats.getByTestId('preview-health')).toHaveText('100/100')
	await page.keyboard.press('Escape')
	await page.locator('[data-cell="7"]').click()
	await page.keyboard.press('i')
	await expect(stats).toBeVisible()
	await expect(stats.getByTestId('preview-health')).toHaveCount(0)
	await page.keyboard.press('Escape')
	await page.getByRole('button', { name: 'Options and help', exact: true }).click()
	const options = page.getByRole('dialog', { name: 'Options and help', exact: true })
	await options.locator('summary').filter({ hasText: 'How to play' }).click()
	await expect(options.locator('dl > div').filter({ hasText: 'Cell statistics' }).locator('dd')).toHaveText('I')
	await page.keyboard.press('i')
	await expect(stats).toHaveCount(0)
	await expect(options).toBeVisible()
})
